version: '3'
services:
  frontend:
    image: ${DOCKER_USERNAME}/syu-voltup-frontend:latest
    container_name: syu-voltup-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    image: ${DOCKER_USERNAME}/syu-voltup-backend:latest
    container_name: syu-voltup-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
